export const PELIGROS: Record<string, string[]> = {
    BIOLOGICOS: [
      "VIRUS",
      "BACTERIAS",
      "HONGOS",
      "RICKTESIAS",
      "PARASITOS",
      "PICADURAS",
      "MORDEDURAS",
      "FLUIDOS O EXCREMENTOS",
    ],
    FISICOS: [
      "RUIDO (DE IMPACTO, INTERMITENTE O CONTINUO)",
      "ILUMINACION (LUZ EN EXCESO O AUSENCIA)",
      "VIBRACION (CUERPO ENTERO O SEGMENTARIA)",
      "EXPOSICION TEMPERATURAS EXTREMAS (FRIO O CALOR)",
      "CONTACTOS TERMICOS",
      "RADIACION IONIZANTE (RAYOS X, GAMA)",
      "RADIACION NO IONIZANTE (LASER, UV, IR)",
      "PRESIONES EXTREMAS (ALTA O BAJA)",
    ],
    QUIMICOS: [
      "POLVOS ORGANICOS O INORGANICOS",
      "LIQUIDOS (NIEBLAS Y ROCIOS)",
      "GASES Y VAPORES",
      "MATERIAL PARTICULADO",
    ],
    PSICOSOCIALES: [
      "GESTION ORGANIZACIONAL (ESTILO DE MANDO, PAGO, BIENESTAR SOCIAL, EVALUACION DEL DESEMPEÑO, MANEJO DE CAMBIOS)",
      "CARACTERISTICAS DE LA ORGANIZACIÓN DEL TRABAJO (COMUNICACIÓN, TECNOLOGIA, ORGANIZACION DEL TRABAJO, DEMANDAS CUALITATIVAS Y CUANTITATIVAS DE LA LABOR)",
      "CARACTERISTICAS DEL GRUPO SOCIAL DEL TRABAJO (RELACIONES, COHESION, CALIDAD DE INTERACCION, TRABAJO EN EQUIPO)",
      "CONDICIONES DE LA TAREA (CARGA MENTAL, CONTENIDO DE LA TAREA, DEMANDAS EMOCIONALES, SISTEMAS DE CONTROL, DEFINICION DE ROLES, MONOTONIA, ETC.)",
      "INTERFASE PERSONA - TAREA (CONOCIMIENTOS, HABILIDAD EN RELACION CON LA DEMANDA DE LA TAREA, INICIATIVA, AUTONOMIA Y RECONOCIMIENTO, IDENTIFICACION DE LA PERSONA CON LA TAREA Y LA ORGANIZACIÓN)",
      "JORNADA DE TRABAJO (PAUSAS, TRABAJO NOCTURNO, ROTACION, HORAS EXTRA, DESCANSO)",
    ],
    BIOMECANICOS: [
      "POSTURA (PROLONGADA, MANTENIDA, FORZADA, ANTIGRAVITACIONAL)",
      "ESFUERZO",
      "MOVIMIENTO REPETITIVO",
      "MANIPULACION MANUAL DE CARGAS",
    ],
    "CONDICIONES DE SEGURIDAD": [
      "MECANICOS (ELEMENTOS O PARTES DE MAQUINAS, HERRAMIENTAS, EQUIPOS, PIEZAS A TRABAJAR, MATERIALES PROYECTADOS SOLIDOS O FLUIDOS)",
      "ELECTRICO (ALTA Y BAJA TENSION, ESTATICA)",
      "LOCATIVO (SISTEMAS Y MEDIOS DE ALMACENAMIENTO) SUPERFICIES DE TRABAJO (IRREGULARIDAD, DESLIZANTE, CON DIFERENCIA DEL NIVEL) CONDICIONES DE ORDEN Y ASEO (CAIDAS DE PERSONAS AL MISMO U OTRO NIVEL)",
      "TECNOLOGICO (EXPLOSION, FUGA, DERRAME, INCENDIO)",
      "ATROPELLO O GOLPE DE PERSONAS CON VEHICULO",
      "PUBLICOS (ROBOS, ATRACOS, ASALTOS, ATENTADOS, DE ORDEN PUBLICO, ETC.)",
      "TRABAJO EN ALTURAS",
      "ESPACIOS CONFINADOS",
    ],
    "FENOMENOS NATURALES": [
      "SISMO",
      "TERREMOTO",
      "VENDAVAL",
      "INUNDACION",
      "DERRUMBE",
      "PRECIPITACIONES (LLUVIAS, GRANIZADAS, HELADAS)",
    ],
  }
  
  export const ND_OPTIONS = [
    { label: "Muy Alto (MA)", value: "MA", nd: 10 },
    { label: "Alto (A)", value: "A", nd: 6 },
    { label: "Medio (M)", value: "M", nd: 2 },
    // Bajo (B) en el Excel “no asigna valor”; en app lo tratamos como 0 para cálculo.
    { label: "Bajo (B)", value: "B", nd: 0 },
  ] as const
  
  export const NE_OPTIONS = [
    { label: "Continua (EC)", value: "EC", ne: 4 },
    { label: "Frecuente (EF)", value: "EF", ne: 3 },
    { label: "Ocasional (EO)", value: "EO", ne: 2 },
    { label: "Esporádica (EE)", value: "EE", ne: 1 },
  ] as const
  
  export const NC_OPTIONS = [
    { label: "Mortal o catastrófico (M)", value: "M", nc: 100 },
    { label: "Muy grave (MG)", value: "MG", nc: 60 },
    { label: "Grave (G)", value: "G", nc: 25 },
    { label: "Leve (L)", value: "L", nc: 10 },
  ] as const
  